#
# SL2Reps: Constructs representations of SL2(Z).
#
# Representations of type R.


#! @Chapter Irreps

#! @Section Representations of type R
#!
#! See Section <Ref Sect="Chapter_Description_Section_Weil_Subsection_Type_R"/>.


#! @Arguments p,ld,sigma,r,t
#! @Returns a record `rec(Agrp, Bp, Char, IsPrim, Nm, Ord, Prod, c, tM)` describing $(M,Q)$
#! @Description
#!  Constructs information about the underlying quadratic module $(M,Q)$ of type $R$, for
#!  $p$ a prime. The additional parameters $\lambda$, $\sigma$, $r$, and $t$ should
#!  be integers chosen as follows.
#!
#!  If $p$ is an odd prime, let $\lambda \geq 2$, $\sigma \in \{1, \dots, \lambda - 1\}$,
#!  and $r,t \in \{1,u\}$ with $u$ a quadratic non-residue mod $p$.  Note that $\sigma = \lambda$
#!  is a valid choice for type $R$, however, this gives the unary case, and so is not handled by this
#!  function, as it is decomposed in a different way; for this case, use <Ref Func="SL2IrrepRUnary"/> instead.
#!
#!  If $p=2$, let $\lambda \geq 2$, $\sigma \in \{0, \dots, \lambda-2\}$ and $r,t \in \{1,3,5,7\}$.
#!
#!  `Agrp` is a list describing the elements of
#!  \[\mathfrak{A} = \{\varepsilon \in M^\times \mid \operatorname{Nm}(\varepsilon) = 1 \}\]
#!  (see <Cite Key="NW76" Where="Section 2.3 - 2.5"/>). The group $\mathfrak{A}$ has the following form.
#!
#!  First consider the special case $p = 2$ and $\sigma = \lambda - 2$.  If $\lambda = 4$,
#!  then $\mathfrak{A} \cong \mathbb{Z}/2\mathbb{Z}$, generated by $\zeta = 7$; for simplicity we say $\alpha = 1$.
#!  Otherwise, $\mathfrak{A} = \langle\alpha\rangle \times \langle\zeta\rangle$
#!  with $\zeta = -1$ and $\alpha \neq \zeta$ of order 2.
#!
#!  Each element $a$ of $\mathfrak{A}$ is represented in `Agrp` by a list `[v, a]`,
#!  where `v` is a list defined by $a = \alpha^{\mathtt{v[1]}} \zeta^{\mathtt{v[2]}}$.
#!
#!  `Bp` is a list of representatives for the $\mathfrak{A}$-orbits on $M^\times$, which
#!  correspond to a basis for the $\mathrm{SL}_2(\mathbb{Z}/p^\lambda\mathbb{Z})$-invariant subspace
#!  associated to any primitive character $\chi \in \widehat{\mathfrak{A}}$ with $\chi^2 \not\equiv 1$.
#!  For other characters, we must use different bases which are particular to each case.
#!
#!  `Char(i,j)` converts two integers $i$, $j$ to a function representing a character of $\mathfrak{A}$.
#!  Each character in $\hat{\mathfrak{A}}$ is of the form $\chi_{i,j}$, given by
#!  \[\chi_{i,j}(\alpha^{v}\zeta^{w}) \mapsto \mathbf{e}\left(\frac{vi}{|\alpha|}\right) \mathbf{e}\left(\frac{wj}{|\zeta|}\right)~.\]
#!  Note that $i$ is irrelevant in the cases where $\mathfrak{A}$ is cyclic.
#!
#!  `IsPrim(chi)` tests whether the output of `Char(i,j)` represents a primitive character.
#!  As a special case, for $p=2$, $\lambda \geq 5$, $\sigma = \lambda - 2$, a character is primitive if $\chi(\alpha) = -1$
#!  (this case differs from the usual definition of primitivity; see <Cite Key="NW76" Where="Section 2.5"/>).
#!  For all other cases, a character is primitive if it is injective on $\langle\omicron\rangle \leq \mathfrak{A}$,
#!  where $\omicron$ is defined as follows.
#!
#!  First suppose $p = 2$.  If $\lambda = 4$, $\sigma = 2$, then $\omicron = \alpha$.
#!
#!  `Nm(a)`, `Ord(a)`, and `Prod(a,b)` are the norm, order, and product functions on $M$, respectively.
#!
#!  `c` is a scalar used in calculating the $S$-matrix; namely
#!  $c = \frac{1}{|M|} \sum_{x \in M} \mathbf{e}(Q(x))$.
#!  Note that this is equal to $S_Q(-1) / \sqrt{|M|}$, where
#!  $S_Q(-1) = \frac{1}{\sqrt{|M|}} \sum_{x \in M} \mathbf{e}(Q(x))$
#!  is also known as the central charge.
#!
#!  `tM` is a list describing the elements of the group $M - pM$.






#! @Arguments p,ld,sigma,r,t
#! @Returns a record `rec(Agrp, Char, IsPrim, Nm, Ord, Prod, c, tM)` describing $(M,Q)$
#! @Description
#!  Constructs information about the underlying quadratic module $(M,Q)$ of type $R$, for
#!  $p$ a prime, $\lambda \geq 1$.  See
#!
#!  `Agrp` describes the elements of $\mathfrak{A} = \{\varepsilon \in M^\times \mid \operatorname{Nm}(\varepsilon) = 1 \}$
#!  (see <Cite Key="NW76" Where="Section 2.3 - 2.5"/>).
#!
#!  Representatives for the $\mathfrak{A}$-orbits on $M^\times$ can depend on the choice of
#!  character, even for primitive characters $\chi$ with $\chi^2 \not\equiv 1$.  Thus, we
#!  cannot provide them here, and they are instead calculated by <Ref Func="SL2IrrepR"/>.
#!
#!  `Char(i,j)` converts the `chi_index` used in <Ref Func="SL2IrrepR"/> to a function.
#!
#!  `IsPrim(chi)` tests whether a given character (e.g. from `Char`) is primitive.
#!
#!  `Nm(a)`, `Ord(a)`, and `Prod(a,b)` are the norm, order, and product functions on $M$, respectively.
#!
#!  `c` is a scalar used in calculating the $S$-matrix; namely $c = \frac{1}{|M|} \sum_{x \in M} \mathbf{e}(Q(x))$.
#!
#!  `tM` is the group $M - pM$.
DeclareGlobalFunction( "SL2ModuleR" );

#! @Arguments p,ld,sigma,r,t,chi_index
#! @Returns a list of lists of the form $[S,T]$
#! @Description
#!  Constructs the modular data for the irreducible representation(s) of type $R$ with
#!  parameters $p$, $\lambda$, $\sigma$, $r$, $t$ as described in <Ref Func="SL2ModuleN"/>,
#!  corresponding to the character $\chi$ indexed by `chi_index = [i,j]`
#!  (see the discussions of $\sigma$, $r$, $t$, and `Char(i,j)` in <Ref Func="SL2ModuleN"/>).
#!
#!  Depending on the parameters, $W(M,Q)$ will contain either 1 or 2 such irreps.
#!
#!  If $\sigma = \lambda$ for $p \neq 2$, then the second factor of $M$ is trivial
#!  (and hence $t$ is irrelevant) so this falls through to <Ref Func="SL2IrrepRUnary"/>.
DeclareGlobalFunction( "SL2IrrepR" );

#! @Arguments p,ld,r
#! @Returns a list of lists of the form $[S,T]$
#! @Description
#!  Constructs the modular data for the irreducible representation(s) of unary type $R$
#!  (that is, the special case where $\sigma = \lambda$) with $p$ an odd prime,
#!  $\lambda$ a positive integer, and $r \in \{1,u\}$ with $u$ a quadratic non-residue mod $p$.
#!
#!  In this case, $W(M,Q)$ always contains exactly 2 such irreps.
DeclareGlobalFunction( "SL2IrrepRUnary" );
