#
# SL2Reps: Constructs representations of SL2(Z).
#
# Representations of type N.

#! @Chapter Irreps

#! @Section Representations of type N
#!
#! See <Ref Sect="Chapter_Description_Section_Weil_Subsection_Type_N"/>.


#! @Arguments p,ld
#! @Returns a record `rec(Agrp, Bp, Char, IsPrim, Nm, Prod)` describing $(M,Q)$
#! @Description
#!  Constructs information about the underlying quadratic module $(M,Q)$ of type $N$.
#!
#!  `Agrp` is a list describing the elements of $\mathfrak{A} = \{\varepsilon \in M^\times \mid \operatorname{Nm}(\varepsilon) = 1 \}$
#!  (see <Cite Key="NW76" Where="Section 2.2"/>). The group $\mathfrak{A}$ has the following form.
#!  When $\lambda \geq 2$, it is generated by $\alpha$ and $\zeta$:
#!  for $p=2$, $|\alpha| = 2^{\lambda-2}$ and $|\zeta| = 6$, while for $p \neq 2$,
#!  $|\alpha| = p^{\lambda-1}$ and $|\zeta| = p+1$.  On the other hand, when $\lambda = 1$,
#!  $\mathfrak{A}$ is cyclic; in this case, we choose a generator $\zeta$
#!  with $|\zeta| = p+1$ and (for simplicity) say $\alpha = 1$.
#!  Each element $a$ of $\mathfrak{A}$ is represented in `Agrp` by a list `[v, a]`,
#!  where `v` is a list defined by $a = \alpha^{\mathtt{v[1]}} \zeta^{\mathtt{v[2]}}$.
#!
#!  `Bp` is a list of representatives for the $\mathfrak{A}$-orbits on $M^\times$, which
#!  correspond to a basis the $\mathrm{SL}_2(\mathbb{Z}/p^\lambda\mathbb{Z})$-invariant subspace
#!  associated to any primitive character $\chi \in \hat{\mathfrak{A}}$ with $\chi^2 \not\equiv 1$.
#!  For other characters, we must use different bases which are particular to each case.
#!
#!  `Char(i,j)` converts two integers $i$, $j$ to a function representing a character of $\mathfrak{A}$.
#!  Each character in $\hat{\mathfrak{A}}$ is of the form $\chi_{i,j}$, given by
#!  \[\chi_{i,j}(\alpha^{v}\zeta^{w}) \mapsto \mathbf{e}\left(\frac{vi}{|\alpha|}\right) \mathbf{e}\left(\frac{wj}{|\zeta|}\right)~.\]
#!  Note that $i$ is irrelevant in the cases where $\mathfrak{A}$ is cyclic.
#!
#!  `IsPrim(chi)` tests whether the output of `Char(i,j)` represents a primitive character.
#!
#!  `Nm(a)` and `Prod(a,b)` are the norm and product functions on $M$, respectively.
DeclareGlobalFunction( "SL2ModuleN" );

#! @Arguments p,ld,chi_index
#! @Returns a list of lists of the form $[S,T]$
#! @Description
#!  Constructs the modular data for the irreducible representation(s) of type $N$ with
#!  level $p^\lambda$ corresponding to the character $\chi$ indexed by `chi_index = [i,j]`
#!  (see the discussion of `Char(i,j)` in <Ref Func="SL2ModuleN"/>).
#!
#!  Depending on the parameters, $W(M,Q)$ will contain either 1 or 2 such irreps.
DeclareGlobalFunction( "SL2IrrepN" );
